Rewrite tests to Page Object Model
kubewarden/ui pull request #357
Opened 2023-05-18 10:30 UTC by kravciak

Initial rewrite of tests to POM.
- added rancher UI helpers to work with custom elements (checkboxes, ...)
- split installation tests and basic landing page checks
- added rancher-common helpers (adding repos, installing apps, login, ...)
- multiple test stability & readability improvements

2023-05-22 13:30 UTC, viccuad approved these changes
LGTM from the test side point (I don't have anything to add from the Typescript point)

2023-05-23 12:06 UTC, jordojordo requested changes
One minor change, and a few suggestions - Otherwise looks good

2023-05-23 12:06 UTC, jordojordo commented on tests/playwright.config.ts
> +  workers: process.env.CI ? 1 : 1,
Should this be always returning `1` regardless of the `process.env.CI`?

2023-05-23 12:06 UTC, jordojordo commented on tests/e2e/exec.spec.ts
> +]
This is a typescript-ism, not necessary but could be good in the long run when using this object elsewhere; you can turn `charts` into an [`interface`](https://www.typescriptlang.org/docs/handbook/2/objects.html) - this will give more insight into the definition of properties within these charts.

2023-05-23 12:06 UTC, jordojordo commented on tests/e2e/pages/rancher-common.page.ts
> +  async installApp(name: string, options?: {namespace?: string, project?: string, validate: string}) {
The props here would be a good use case for turning the `charts` object in `./e2e/exec.spec.ts` into an `interface`.

2023-05-23 23:03 UTC, kravciak commented on tests/playwright.config.ts
> +  workers: process.env.CI ? 1 : 1,
fixed

2023-05-24 12:22 UTC, kravciak commented on tests/e2e/exec.spec.ts
> +]
I added another commit fixing this, thanks for the suggestion!

2023-05-24 12:34 UTC, jordojordo approved these changes
Looks good!

2023-05-24 12:50 UTC, merged